#!/usr/bin/env python3
import argparse
import json
import re
from pathlib import Path

import yaml


KEY_COUNT = 54
REPORT_MAGIC = b"SL54LYR"

ALIASES = {
    "___": "KC_TRNS",
    "TRNS": "KC_TRNS",
    "---": "KC_NO",
    "NO": "KC_NO",
    "Esc": "KC_ESC",
    "Tab": "KC_TAB",
    "Ctrl": "KC_LCTL",
    "Shift": "KC_LSFT",
    "GUI": "KC_LGUI",
    "Alt": "KC_LALT",
    "Space": "KC_SPC",
    "Enter": "KC_ENT",
    "Bspc": "KC_BSPC",
    "Del": "KC_DEL",
    "Ins": "KC_INS",
    "Home": "KC_HOME",
    "End": "KC_END",
    "PgUp": "KC_PGUP",
    "PgDn": "KC_PGDN",
    "Left": "KC_LEFT",
    "Down": "KC_DOWN",
    "Up": "KC_UP",
    "Right": "KC_RGHT",
    "Boot": "QK_BOOT",
    "Caps": "KC_CAPS",
    "Menu": "KC_APP",
    "Mute": "KC_MUTE",
    "Vol-": "KC_VOLD",
    "Vol+": "KC_VOLU",
    "Prev": "KC_MPRV",
    "Next": "KC_MNXT",
    "Play": "KC_MPLY",
    ",": "KC_COMM",
    ".": "KC_DOT",
    "/": "KC_SLSH",
    "-": "KC_MINS",
    "'": "KC_QUOT",
    ";": "KC_SCLN",
    "`": "KC_GRV",
    "\\": "KC_BSLS",
    "[": "KC_LBRC",
    "]": "KC_RBRC",
    "=": "KC_EQL",
    "!": "KC_EXLM",
    "@": "KC_AT",
    "#": "KC_HASH",
    "$": "KC_DLR",
    "%": "KC_PERC",
    "^": "KC_CIRC",
    "&": "KC_AMPR",
    "*": "KC_ASTR",
    "(": "KC_LPRN",
    ")": "KC_RPRN",
    "_": "KC_UNDS",
    "+": "KC_PLUS",
    "{": "KC_LCBR",
    "}": "KC_RCBR",
    "|": "KC_PIPE",
    ":": "KC_COLN",
    '"': "KC_DQUO",
    "<": "KC_LT",
    ">": "KC_GT",
    "?": "KC_QUES",
    "~": "KC_TILD",
}


def c_ident(name):
    return "_" + re.sub(r"[^A-Za-z0-9_]", "_", name).upper()


def qmk_keycode(label, layer_indices):
    label = str(label)
    if label in layer_indices:
        return f"MO({c_ident(label)})"
    if label in ALIASES:
        return ALIASES[label]
    if re.fullmatch(r"[A-Z]", label):
        return f"KC_{label}"
    if re.fullmatch(r"[0-9]", label):
        return f"KC_{label}"
    if re.fullmatch(r"F([1-9]|1[0-9]|2[0-4])", label):
        return f"KC_{label}"
    if label.startswith("KC_") or label.startswith("QK_") or "(" in label:
        return label
    raise ValueError(f"no QMK keycode alias for {label!r}")


def render_layer(name, keys, layer_indices):
    codes = [qmk_keycode(key, layer_indices) for key in keys]
    rows = [
        codes[0:12],
        codes[12:24],
        codes[24:36],
        codes[36:48],
        codes[48:54],
    ]
    rendered_rows = []
    for row in rows:
        rendered_rows.append("        " + ", ".join(f"{code:<8}" for code in row))
    return f"    [{c_ident(name)}] = LAYOUT(\n" + ",\n".join(rendered_rows) + "\n    )"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--keymap", required=True, type=Path)
    parser.add_argument("--output-c", required=True, type=Path)
    parser.add_argument("--output-metadata", required=True, type=Path)
    args = parser.parse_args()

    data = yaml.safe_load(args.keymap.read_text())
    layers = data["layers"]
    layer_names = list(layers.keys())
    layer_indices = {name: index for index, name in enumerate(layer_names)}

    for name, keys in layers.items():
        if len(keys) != KEY_COUNT:
            raise ValueError(f"layer {name!r} has {len(keys)} keys, expected {KEY_COUNT}")

    layer_enum = ",\n".join(f"    {c_ident(name)} = {index}" for name, index in layer_indices.items())
    rendered_layers = ",\n\n".join(render_layer(name, keys, layer_indices) for name, keys in layers.items())
    magic_bytes = ", ".join(str(byte) for byte in REPORT_MAGIC)

    args.output_c.write_text(
        f"""// Generated from keymap.yaml. Do not edit this file by hand.
#include QMK_KEYBOARD_H

#ifdef RAW_ENABLE
#    include "raw_hid.h"
#endif

#ifndef RAW_EPSIZE
#    define SILAKKA54_RAW_EPSIZE 32
#else
#    define SILAKKA54_RAW_EPSIZE RAW_EPSIZE
#endif

enum silakka54_layers {{
{layer_enum}
}};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {{
{rendered_layers}
}};

const char chordal_hold_layout[MATRIX_ROWS][MATRIX_COLS] PROGMEM =
    LAYOUT(
        'L', 'L', 'L', 'L', 'L', 'L',  'R', 'R', 'R', 'R', 'R', 'R',
        'L', 'L', 'L', 'L', 'L', 'L',  'R', 'R', 'R', 'R', 'R', 'R',
        'L', 'L', 'L', 'L', 'L', 'L',  'R', 'R', 'R', 'R', 'R', 'R',
        'L', 'L', 'L', 'L', 'L', 'L',  'R', 'R', 'R', 'R', 'R', 'R',
                       'L', 'L', 'L',  'R', 'R', 'R'
    );

static uint8_t reported_layer = 0xFF;

static void silakka54_send_layer_report(uint8_t layer) {{
#ifdef RAW_ENABLE
#    ifdef SPLIT_KEYBOARD
    if (!is_keyboard_master()) {{
        return;
    }}
#    endif
    uint8_t report[SILAKKA54_RAW_EPSIZE] = {{0}};
    const uint8_t magic[] = {{{magic_bytes}}};
    for (uint8_t i = 0; i < sizeof(magic); i++) {{
        report[i] = magic[i];
    }}
    report[7] = 1;
    report[8] = layer;
    raw_hid_send(report, SILAKKA54_RAW_EPSIZE);
#endif
}}

void keyboard_post_init_user(void) {{
    reported_layer = get_highest_layer(layer_state);
    silakka54_send_layer_report(reported_layer);
}}

layer_state_t layer_state_set_user(layer_state_t state) {{
    uint8_t layer = get_highest_layer(state);
    if (layer != reported_layer) {{
        reported_layer = layer;
        silakka54_send_layer_report(layer);
    }}
    return state;
}}
"""
    )

    args.output_metadata.write_text(
        json.dumps(
            {
                "packet_magic": REPORT_MAGIC.decode(),
                "packet_version": 1,
                "layers": [{"index": index, "name": name} for name, index in layer_indices.items()],
            },
            indent=2,
        )
        + "\n"
    )


if __name__ == "__main__":
    main()
