{
  lib,
  inputs,
  config,
  ...
}:

let
  cfg = config.corncheese.development;
  githubAccessInclude = "!include ${config.age.secrets."corncheese.github.token".path}";
  determinateConfigLib =
    import "${inputs.determinate.outPath}/modules/nix-darwin/config/config.nix" {
      inherit lib;
    };
in
{
  imports = [
    inputs.determinate.darwinModules.default
  ];

  options = {
    corncheese.development = {
      enable = lib.mkEnableOption "corncheese development environment";
      githubAccess.enable = lib.mkEnableOption "GitHub access token for the Nix daemon";
      remoteBuilders.enable = lib.mkEnableOption "corncheese remote builders";
    };
  };

  config = lib.mkMerge [
    (lib.mkIf (cfg.enable || cfg.githubAccess.enable) {
      age.secrets = {
        "corncheese.github.token" = {
          rekeyFile = lib.repoSecret "corncheese/github/token.age";
          owner = config.system.primaryUser;
          mode = "400";
        };
      };

      environment.etc."nix/nix.custom.conf".text = lib.mkForce (
        lib.concatStringsSep "\n" (
          [
            "# This custom configuration file for Determinate Nix is generated by the determinate module for nix-darwin."
            "# Update your custom settings by changing your nix-darwin configuration, not by modifying this file directly."
            ""
          ]
          ++ determinateConfigLib.mkCustomConfig config.determinateNix.customSettings
          ++ [ githubAccessInclude ]
        )
      );
    })
    (lib.mkIf cfg.enable {
      determinateNix = {
        enable = true;
        customSettings = {
          eval-cores = 0;
          extra-experimental-features = [
            "external-builders"
            "parallel-eval"
          ];
          inherit (config.nix.settings)
            extra-substituters
            extra-trusted-public-keys
            trusted-substituters
            trusted-users
            ;
        };
      };
      nix = {
        # Let Determinate Nix handle Nix configuration rather than nix-darwin
        enable = false;

        # This will add each flake input as a registry
        # To make nix3 commands consistent with your flake
        registry = lib.mapAttrs (_: value: { flake = value; }) inputs;

        # This will additionally add your inputs to the system's legacy channels
        # Making legacy nix commands consistent as well, awesome!
        nixPath = lib.mapAttrsToList (key: value: "${key}=${value.to.path}") config.nix.registry;

        settings = {
          trusted-users = [ "root" ];
          extra-substituters = [
            "https://cache.nixos.org"
          ];
          extra-trusted-public-keys = [
            "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
          ];
        };
      };
    })
    (lib.mkIf cfg.remoteBuilders.enable {
      age.secrets = {
        "corncheese.home.key" = {
          rekeyFile = lib.repoSecret "corncheese/home/key.age";
          mode = "400";
        };
      };
      programs.ssh = {
        extraConfig = ''
          # bigbrain-direct
          Host home.conroycheers.me
            User conroy
            HostName home.conroycheers.me
            Port 8022
            IdentityFile ${config.age.secrets."corncheese.home.key".path}
        '';
      };
      determinateNix.customSettings.builders-use-substitutes = true;
    })
  ];
}
