name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v17
    - uses: cachix/cachix-action@v16
      with:
        name: corncheese
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check -vL
